### ISSUE TITLE
Purpose of chatbot 

### ISSUE THREAD

**Issue by samreenkazi** [irdanish11/Seq2Seq-UrduChatBot#1]
dear danish
how does this chatbot work? is it question answer engine?

**Comment by irdanish11** [comment]
The chatbot is build using Seq2Seq model. It can answer some of the general questions like you can ask weather, date, time of 200+ international cities and all the districts of Pakistan. It can entertain to you with some jokes or poetry. You can download the installer from the following link, read carefully the prerequisites and install them to run the chatbot properly.
https://drive.google.com/open?id=1EL7UAXV7BI67EZsT46EllyHfAhA4IPv6
Below are some of the sample responses of our chatbot.
![1](https://user-images.githubusercontent.com/19354208/61812175-6a96c200-ae5c-11e9-9027-d5c6183d9c1c.jpg)
![2](https://user-images.githubusercontent.com/19354208/61812187-71bdd000-ae5c-11e9-9014-55c332adbd57.jpg)
![3](https://user-images.githubusercontent.com/19354208/61812191-75e9ed80-ae5c-11e9-822b-f2fc91bc4e2e.jpg)
![4](https://user-images.githubusercontent.com/19354208/61812210-7a160b00-ae5c-11e9-9580-ab3dca331f8d.jpg)
![5](https://user-images.githubusercontent.com/19354208/61812220-800bec00-ae5c-11e9-800c-75e436dd2f72.jpg)
